Нужно больше функций
htmlacademy-javascript/2174005-kekstagram-28 pull request #2
Opened 2023-02-22 09:17 UTC by lena-lis

---
:mortar_board: [Нужно больше функций](https://up.htmlacademy.ru/javascript/28/user/2174005/tasks/7)

:boom: https://htmlacademy-javascript.github.io/2174005-kekstagram-28/2/

2023-02-23 07:15 UTC, babtshe requested changes
Хорошо бы поправить ошибки линтера:
<img width="898" alt="image" src="https://user-images.githubusercontent.com/30229773/220841356-2801a2b7-19bc-479c-ae3d-6f9c9a3ae4b2.png">
Падающие тесты гарантируют отправку домашки на доработку.

2023-02-23 07:15 UTC, babtshe commented on js/functions.js
> +function validateString (string, maxLength) {
см [критерий](https://up.htmlacademy.ru/javascript/28/criteries#d5)

2023-02-23 07:45 UTC, lena-lis commented on js/functions.js
> +function validateString (string, maxLength) {
Спасибо, всё поправлю!

2023-02-24 07:32 UTC, babtshe approved these changes

2023-02-24 07:32 UTC, babtshe commented on js/functions.js
> +    if (parseInt(string[i], 10) === Number(string[i])) {
Так лучше не делать, это костыль, построенный на том, что `NaN === NaN // false`
Оптимально будет явно убедиться в том, что в результате парсинга мы получили число, а не `NaN`

2023-02-24 07:32 UTC, merged