Module8 task1
htmlacademy-javascript/2174005-kekstagram-28 pull request #6
Opened 2023-03-24 06:42 UTC by lena-lis

2023-03-24 08:10 UTC, babtshe requested changes

2023-03-24 08:10 UTC, babtshe commented on js/full-size-picture.js
> +}
На защите могут ошибочно придраться к [критерию](https://up.htmlacademy.ru/javascript/28/criteries#d5), но тут всё корректно, ничего менять не нужно.

2023-03-24 08:10 UTC, babtshe commented on js/full-size-picture.js
> +    commentsContainer.append(newComment);
лучше не допускать таких неявных присваиваний в функции. Оптимально будет либо вернуть новый фрагмент из функции, либо передать переменную с контейнером через параметры. В будущем такой подход значительно упростит тестирование.

2023-03-24 08:10 UTC, babtshe commented on js/full-size-picture.js
> +  bigImage.querySelector('img').src = url;
Точно ли тут необходимо искать этот элемент повторно при каждом вызове функции? См [критерий](https://up.htmlacademy.ru/javascript/28/criteries#d21)

2023-03-24 08:10 UTC, babtshe commented on js/thumbnail.js
> +const renderThumbnails = createPhotos();
судя по названию, переменная ссылается на функцию, а на самом деле это не так.

2023-03-27 06:59 UTC, lena-lis commented on js/full-size-picture.js
> +}
Я понимаю, но здесь все сделано строго по демке самой Академии. Пробовала переписать на стрелочных функциях, но тогда возникает проблема с их объявлением и линтер ругается.

2023-03-27 15:42 UTC, babtshe approved these changes

2023-03-27 15:43 UTC, merged